name: E2E Tests Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # adds manual trigger button

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Linux package
        env:
          ELECTRON_BUILDER_PUBLISH: never
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:linux

      - name: Install app
        run: sudo apt install -y ./dist/timetrackingapp_*.deb

      - name: Install Xvfb
        run: sudo apt install -y xvfb

      - name: Run E2E tests
        run: Xvfb :99 -screen 0 1024x768x24 & sleep 1 && DISPLAY=:99 npx playwright test --config=e2e/playwright.config.ts
